### ISSUE TITLE
float() argument must be a string or a number, not 'DegreeView'

### ISSUE THREAD

**Issue by idimitriadis** [taynaud/python-louvain#38]
Hello! I have created an undirected attributed graph with ~300K nodes that works fine with all the networkx modules. I am trying to use the community_louvain.best partition algorithm but i keep getting the error:

> line 50, in init
    deg = float(graph.degree(node, weight=weight))
TypeError: float() argument must be a string or a number, not 'DegreeView'

I tried to see what is wrong and i found out that when calling the graph.degree function networkx returns an int if you are searching for a specific node and a DegreeView object if you are searching for a bunch of nodes. I guess that this is not covered by the already available implementation? 
I use networkx 2.2 and python_louvain 0.13. 
Anybody that faces the same issue? 

Thank you in advance!

**Comment by PiggyGaGa** [comment]
I met this error, but change another network it will not appear,  But I think the problem is my network, except this issue, when I calculate avg_clustering(), it also came accross an error, I debug the source code, finally, I found that my network had "None" node. When we use nx.Graph() and add nodes or edges normally, no problem. But if we add node "None"  or add edge(*, None), it will appear this kind of problem. That is my problem. You can also check out your own network if there exist "None" node.

**Comment by PiggyGaGa** [comment]
> Hello! I have created an undirected attributed graph with ~300K nodes that works fine with all the networkx modules. I am trying to use the community_louvain.best partition algorithm but i keep getting the error:
> 
> > line 50, in init
> > deg = float(graph.degree(node, weight=weight))
> > TypeError: float() argument must be a string or a number, not 'DegreeView'
> 
> I tried to see what is wrong and i found out that when calling the graph.degree function networkx returns an int if you are searching for a specific node and a DegreeView object if you are searching for a bunch of nodes. I guess that this is not covered by the already available implementation?
> I use networkx 2.2 and python_louvain 0.13.
> Anybody that faces the same issue?
> 
> Thank you in advance!

I have the similar problem, and solved it , you can try it~
