### ISSUE TITLE
Why does the number of clusters decrease when resolution increases?

### ISSUE THREAD

**Issue by ortholog** [taynaud/python-louvain#86]
Normally, with higher resolution, shouldn't the number of clusters increase?

**Comment by ComplexLychee** [comment]
Thanks for pointing out the issue. 

It turns out that there is a mistake in the implementation of the algorithm which is related to the resolution parameter. The algorithm was correctly implemented only when the resolution is one.

As can been seen from my pull request, the problem is in the computation of the change in modularity after alternating the block membership of a node.

**Comment by taynaud** [comment]
Thanks !
